title: Kabir Pathak
email: kabirpathak99@gmail.com
description: >-
  Hello and welcome to my blog. I post all my blogs - tech or non-tech here.
  I usually post one blog per week, so stay tuned!
baseurl: "" 
url: "https://kabirpathak.github.io"
github_username: kabirpathak

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
